{% set name = "ncbi-datasets-cli" %}
{% set version = "12.21.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/release/{{ version }}.tar.gz
  sha256: f455cbbb49ab614cd458ca791b52e896880b2da2f5327a7a327ec127c9ccfb7e

build:
  number: 1
  script: python {{ RECIPE_DIR }}/build.py

requirements:
  build:
    - bazel <4.0.0
    - go >=1.16.4
    - {{ compiler('cxx') }}
  run:
    - ca-certificates

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://github.com/ncbi/datasets/tree/master/pkgs/ncbi-datasets-cli
  license: Public Domain
  license_file: pkgs/ncbi-datasets-cli/LICENSE.md
  summary: 'NCBI Datasets command-line clients'
  description: |
    NCBI Datasets is a new resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - BradHolmes
    - wra3
