{% set name = "ncbi-datasets-cli" %}
{% set version = "12.18.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/release/{{ version }}.tar.gz
  sha256: 5139f47d88a19c5d6f1898847ed441fe16b9c3651051f533af4b8bc27193535a

build:
  number: 0
  script: python {{ RECIPE_DIR }}/build.py

requirements:
  build:
    - bazel <4.0.0
    - go >=1.16.4
    - {{ compiler('cxx') }}

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://github.com/ncbi/datasets/tree/master/pkgs/ncbi-datasets-cli
  license: Public Domain
  license_file: pkgs/ncbi-datasets-cli/LICENSE.md
  summary: 'NCBI Datasets command-line clients'
  description: |
    NCBI Datasets is a new resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - BradHolmes
    - wra3
