{% set name = "ncbi-datasets-cli" %}
{% set version = "12.11.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/release/{{ version }}.tar.gz
  sha256: 4feb6bdad45bffec004292ce171147628919f98cf9c8e4cb6160ccb1f0cb0831

build:
  number: 0
  script: python {{ RECIPE_DIR }}/build.py

requirements:
  build:
    - bazel <4.0.0
    - go >=1.16.4
    - {{ compiler('cxx') }}

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://github.com/ncbi/datasets/tree/master/pkgs/ncbi-datasets-cli
  license: Public Domain
  license_file: pkgs/ncbi-datasets-cli/LICENSE.md
  summary: 'NCBI Datasets command-line clients'
  description: |
    NCBI Datasets is a new resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - BradHolmes
    - wra3