{% set name = "ncbi-datasets-cli" %}
{% set version = "16.15.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/refs/tags/v{{ version }}.tar.gz
  sha256: aecfb0eb5e73158bafa008b0c8507400690a7c0e20c6c0918fe70f62e32c3333

build:
  number: 2
  script: python {{ RECIPE_DIR }}/build.py {{ version }}

requirements:
  run:
    - ca-certificates

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://www.ncbi.nlm.nih.gov/datasets
  license: Public Domain
  license_file: LICENSE.md
  summary: NCBI Datasets command-line clients
  doc_url: https://www.ncbi.nlm.nih.gov/datasets/docs/
  description: |
    NCBI Datasets is a resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - BradHolmes
    - wra3
