{% set name = "ncbi-datasets-cli" %}
{% set version = "12.24.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/release/{{ version }}.tar.gz
  sha256: 1f4af06235ed5a4c57b80644c1c3f36bb1dfe78300f2469f0764f0ee0b82e713

build:
  number: 0
  script: python {{ RECIPE_DIR }}/build.py

requirements:
  build:
    - bazel <4.0.0
    - go >=1.16.4
    - {{ compiler('cxx') }}
  run:
    - ca-certificates

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://github.com/ncbi/datasets/tree/master/pkgs/ncbi-datasets-cli
  license: Public Domain
  license_file: pkgs/ncbi-datasets-cli/LICENSE.md
  summary: NCBI Datasets command-line clients
  description: |
    NCBI Datasets is a new resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - BradHolmes
    - wra3
