{% set name = "ncbi-datasets-cli" %}
{% set version = "13.10.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/release/{{ version }}.tar.gz
  sha256: 21ade85f5a3b0c303b53dae9a9725d62e93f95554973223a74af59378d8482d7

build:
  number: 0
  script: python {{ RECIPE_DIR }}/build.py

requirements:
  build:
    - bazel <4.0.0
    - go >=1.16.4
    - {{ compiler('cxx') }}
  run:
    - ca-certificates

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://www.ncbi.nlm.nih.gov/datasets
  license: Public Domain
  license_file: pkgs/ncbi-datasets-cli/LICENSE.md
  summary: NCBI Datasets command-line clients
  description: |
    NCBI Datasets is a new resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - BradHolmes
    - wra3
