{% set name = "ncbi-datasets-cli" %}
{% set version = "14.13.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/refs/tags/v{{ version }}.tar.gz
  sha256: b3e47f14adb4d8f316aaa2139024b1b1f8ad24209962958a6248a257283affd8

build:
  number: 0
  script: python {{ RECIPE_DIR }}/build.py {{ version }}

requirements:
  run:
    - ca-certificates

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://www.ncbi.nlm.nih.gov/datasets
  license: Public Domain
  license_file: LICENSE.md
  summary: NCBI Datasets command-line clients
  doc_url: https://www.ncbi.nlm.nih.gov/datasets/docs/
  description: |
    NCBI Datasets is a new resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - BradHolmes
    - wra3
