{% set name = "ncbi-datasets-cli" %}
{% set version = "16.35.2" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/ncbi/datasets/archive/refs/tags/v{{ version }}.tar.gz
  sha256: e5d845d22dee9422c103aa714a754e97fc850c802ec61a1779a5f8c74df4a5e2

build:
  number: 0
  script: python {{ RECIPE_DIR }}/build.py {{ version }}

requirements:
  run:
    - ca-certificates

test:
  commands:
    - datasets version
    - dataformat version

about:
  home: https://www.ncbi.nlm.nih.gov/datasets
  license: Public Domain
  license_file: LICENSE.md
  summary: NCBI Datasets command-line clients
  doc_url: https://www.ncbi.nlm.nih.gov/datasets/docs/
  description: |
    NCBI Datasets is a resource that lets you easily gather data from across NCBI databases.

extra:
  recipe-maintainers:
    - corneliusroemer
    - BradHolmes
    - wra3
